"""Per-worker configuration generation.

Each worker gets isolated write-data, mod directory, server settings, map
generation settings, and ports. Nothing is shared across workers, and nothing
touches the user's Factorio profile (PLAN.md 0.2, 1.3).
"""

from __future__ import annotations

import json
import secrets
from dataclasses import dataclass, field
from pathlib import Path

from factoriorl.paths import worker_dir

CONFIG_INI_TEMPLATE = """; generated by FactorioRL; worker {worker_id}
[path]
read-data=__PATH__system-read-data__
write-data={write_data}

[other]
check-updates=false
enable-steam-networking=false
; No autosaves. The interval is in minutes of *game* time, so at game.speed 90
; a 60-minute interval fires roughly every 40 seconds of wall clock, and a save
; is a multi-hundred-millisecond stall in the middle of an episode. Episodes of
; several hundred decisions will hit one. Nothing here needs a save: the
; pristine save is recreated at launch and reset restores the scene.
autosave-interval=0
autosave-slots=0

[interface]
show-tips-and-tricks=false
"""

#: Complete deterministic map settings. Partial files are rejected by the
#: engine ("Key ... not found"), so every prototype key is spelled out with
#: its default value; only pollution/enemy_evolution/enemy_expansion are
#: switched off for a quiet peaceful world (PLAN.md: base-game target).
MAP_SETTINGS = {
    "asteroids": {
        "spawning_rate": 1,
        "max_ray_portals_expanded_per_tick": 100,
    },
    "pollution": {
        "enabled": False,
        "diffusion_ratio": 0.02,
        "min_to_diffuse": 15,
        "ageing": 1,
        "expected_max_per_chunk": 150,
        "min_to_show_per_chunk": 50,
        "min_pollution_to_damage_trees": 60,
        "pollution_with_max_forest_damage": 150,
        "pollution_per_tree_damage": 50,
        "pollution_restored_per_tree_damage": 10,
        "max_pollution_to_restore_trees": 20,
        "enemy_attack_pollution_consumption_modifier": 1,
    },
    "enemy_evolution": {
        "enabled": False,
        "time_factor": 0.000004,
        "destroy_factor": 0.002,
        "pollution_factor": 0.0000009,
    },
    "enemy_expansion": {
        "enabled": False,
        "max_expansion_distance": 7,
        "friendly_base_influence_radius": 2,
        "enemy_building_influence_radius": 2,
        "building_coefficient": 0.1,
        "other_base_coefficient": 2.0,
        "neighbouring_chunk_coefficient": 0.5,
        "neighbouring_base_chunk_coefficient": 0.4,
        "max_colliding_tiles_coefficient": 0.9,
        "settler_group_min_size": 5,
        "settler_group_max_size": 20,
        "min_expansion_cooldown": 14400,
        "max_expansion_cooldown": 216000,
    },
    "unit_group": {
        "min_group_gathering_time": 3600,
        "max_group_gathering_time": 36000,
        "max_wait_time_for_late_members": 7200,
        "max_group_radius": 30.0,
        "min_group_radius": 5.0,
        "max_member_speedup_when_behind": 1.4,
        "max_member_slowdown_when_ahead": 0.6,
        "max_group_slowdown_factor": 0.3,
        "max_group_member_fallback_factor": 3,
        "member_disown_distance": 10,
        "tick_tolerance_when_member_arrives": 60,
        "max_gathering_unit_groups": 30,
        "max_unit_group_size": 200,
    },
    "steering": {
        "default": {
            "radius": 1.2,
            "separation_force": 0.005,
            "separation_factor": 1.2,
            "force_unit_fuzzy_goto_behavior": False,
        },
        "moving": {
            "radius": 3,
            "separation_force": 0.01,
            "separation_factor": 3,
            "force_unit_fuzzy_goto_behavior": False,
        },
    },
    "path_finder": {
        "fwd2bwd_ratio": 5,
        "goal_pressure_ratio": 2,
        "max_steps_worked_per_tick": 1000,
        "max_work_done_per_tick": 8000,
        "use_path_cache": True,
        "short_cache_size": 5,
        "long_cache_size": 25,
        "short_cache_min_cacheable_distance": 10,
        "short_cache_min_algo_steps_to_cache": 50,
        "long_cache_min_cacheable_distance": 30,
        "cache_max_connect_to_cache_steps_multiplier": 100,
        "cache_accept_path_start_distance_ratio": 0.2,
        "cache_accept_path_end_distance_ratio": 0.15,
        "negative_cache_accept_path_start_distance_ratio": 0.3,
        "negative_cache_accept_path_end_distance_ratio": 0.3,
        "cache_path_start_distance_rating_multiplier": 10,
        "cache_path_end_distance_rating_multiplier": 20,
        "stale_enemy_with_same_destination_collision_penalty": 30,
        "ignore_moving_enemy_collision_distance": 5,
        "enemy_with_different_destination_collision_penalty": 30,
        "general_entity_collision_penalty": 10,
        "general_entity_subsequent_collision_penalty": 3,
        "extended_collision_penalty": 3,
        "max_clients_to_accept_any_new_request": 10,
        "max_clients_to_accept_short_new_request": 100,
        "direct_distance_to_consider_short_request": 100,
        "short_request_max_steps": 1000,
        "short_request_ratio": 0.5,
        "min_steps_to_check_path_find_termination": 2000,
        "start_to_goal_cost_multiplier_to_terminate_path_find": 2000.0,
        "overload_levels": [0, 100, 500],
        "overload_multipliers": [2, 3, 4],
        "negative_path_cache_delay_interval": 20,
    },
    "max_failed_behavior_count": 3,
    # Required by the loader even though runtime changes go through
    # game.difficulty_settings.
    "difficulty_settings": {"technology_price_multiplier": 1},
}


@dataclass(frozen=True)
class WorkerPorts:
    game: int
    rcon: int


@dataclass
class WorkerSpec:
    """Fully resolved launch specification for one worker."""

    worker_id: str
    ports: WorkerPorts
    map_seed: int = 424242
    rcon_password: str = field(default_factory=lambda: secrets.token_hex(16))

    @property
    def directory(self) -> Path:
        return worker_dir(self.worker_id)

    @property
    def write_data(self) -> Path:
        return self.directory / "write-data"

    @property
    def mod_directory(self) -> Path:
        return self.directory / "mods"

    @property
    def save_path(self) -> Path:
        return self.directory / "save.zip"

    @property
    def config_ini(self) -> Path:
        return self.directory / "config.ini"

    @property
    def server_settings(self) -> Path:
        return self.directory / "server-settings.json"

    @property
    def map_gen_settings(self) -> Path:
        return self.directory / "map-gen-settings.json"

    @property
    def map_settings(self) -> Path:
        return self.directory / "map-settings.json"

    @property
    def console_log(self) -> Path:
        return self.directory / "engine.log"

    @property
    def server_id_file(self) -> Path:
        return self.directory / "server-id.json"

    @property
    def pid_file(self) -> Path:
        """Engine and parent pids, so a later run can recognise an orphan."""
        return self.directory / "worker-pids.json"

    @property
    def rcon_endpoint(self):
        from factoriorl.rcon import RCONEndpoint

        return RCONEndpoint(host="127.0.0.1", port=self.ports.rcon, password=self.rcon_password)

    def write_config_files(self) -> None:
        self.directory.mkdir(parents=True, exist_ok=True)
        self.write_data.mkdir(exist_ok=True)
        self.mod_directory.mkdir(exist_ok=True)

        self.config_ini.write_text(
            CONFIG_INI_TEMPLATE.format(
                worker_id=self.worker_id,
                write_data=str(self.write_data).replace("\\", "/"),
            ),
            encoding="utf-8",
        )

        server_settings = {
            "name": f"factoriorl-{self.worker_id}",
            "description": "FactorioRL worker",
            "max_players": 0,
            "visibility": {"public": False, "lan": False},
            "username": "",
            "password": "",
            "token": "",
            "game_password": "",
            "require_user_verification": False,
            "max_upload_in_kilobytes_per_second": 0,
            "max_upload_slots": 5,
            "minimum_latency_in_ticks": 0,
            "max_heartbeats_per_second": 60,
            "ignore_player_limit_for_returning_players": False,
            # Zero-player stepping: never auto-pause; runtime controls ticks
            # explicitly via game.tick_paused.
            "allow_commands": "true",
            # Disabled for the same reason as in config.ini: an autosave is a
            # multi-hundred-millisecond stall, the interval is game-time so it
            # scales with game.speed, and a long episode will land on one.
            "autosave_interval": 0,
            "autosave_slots": 0,
            "afk_autokick_interval": 0,
            "auto_pause": False,
            "auto_pause_when_players_connect": False,
            "only_admins_can_pause_the_game": False,
            "autosave_only_on_server": True,
        }
        self.server_settings.write_text(json.dumps(server_settings, indent=2), encoding="utf-8")

        map_gen_settings = {
            "width": 0,
            "height": 0,
            "starting_area": 1,
            # Peaceful base-game target; no biters in Phase 0/1 proofs.
            "peaceful_mode": True,
            "autoplace_controls": {
                "coal": {"frequency": 0, "size": 0, "richness": 0},
                "stone": {"frequency": 0, "size": 0, "richness": 0},
                "copper-ore": {"frequency": 0, "size": 0, "richness": 0},
                "iron-ore": {"frequency": 0, "size": 0, "richness": 0},
                "uranium-ore": {"frequency": 0, "size": 0, "richness": 0},
                "crude-oil": {"frequency": 0, "size": 0, "richness": 0},
                # Off, like every other autoplace control. The scene box is
                # painted by Lua from a declared blueprint, so generated water
                # is an *undeclared* obstacle: the engine-free structural
                # validators run their reachability BFS over blueprint entities
                # and cannot see it, so an episode can pass validation as
                # solvable and then be blocked by terrain no generator chose.
                # It was also the largest block on the wire -- the water sweep
                # dominated a ~32 KB observation on tasks that place no
                # resources at all.
                # size 0 removes the water; frequency stays 1 because the ore
                # probability noise expressions divide by the water frequency
                # term, and a zero there fails map generation outright with
                # 'error compiling entity:coal:probability'.
                "water": {"frequency": 1, "size": 0},
                "trees": {"frequency": 0, "size": 0},
                "enemy-base": {"frequency": 0, "size": 0},
            },
            "cliff_settings": {
                "name": "cliff",
                "cliff_elevation_0": 10,
                "cliff_elevation_interval": 40,
                "richness": 0,
            },
            "property_expression_names": {},
            "starting_points": [{"x": 0, "y": 0}],
            "seed": self.map_seed,
        }
        self.map_gen_settings.write_text(json.dumps(map_gen_settings, indent=2), encoding="utf-8")

        self.map_settings.write_text(json.dumps(MAP_SETTINGS, indent=2), encoding="utf-8")

    def manifest(self) -> dict:
        """Run-manifest fragment identifying this worker's environment."""
        return {
            "worker_id": self.worker_id,
            "map_seed": self.map_seed,
            "ports": {"game": self.ports.game, "rcon": self.ports.rcon},
            "directory": str(self.directory),
        }
